<script type="text/javascript" src="themes/yoko/media/js/jquery.min.js"></script>
<script type="text/javascript" src="themes/yoko/media/js/bootstrap.min.js"></script>
<script type="text/javascript" src="themes/yoko/media/js/jquery.easing.1.3.js"></script>
<script type="text/javascript" src="themes/yoko/media/js/jquery.quicksand.js"></script>
<script type="text/javascript" src="themes/yoko/media/js/superfish.js"></script>
<script type="text/javascript" src="themes/yoko/media/js/hoverIntent.js"></script>
<script type="text/javascript" src="themes/yoko/media/js/jquery.hoverdir.js"></script>
<script type="text/javascript" src="themes/yoko/media/js/jquery.flexslider.js"></script>
<script type="text/javascript" src="themes/yoko/media/js/jflickrfeed.min.js"></script>
<script type="text/javascript" src="themes/yoko/media/js/jquery.prettyPhoto.js"></script>
<script type="text/javascript" src="themes/yoko/media/js/jquery.elastislide.js"></script>
<script type="text/javascript" src="themes/yoko/media/js/jquery.tweet.js"></script>
<script type="text/javascript" src="themes/yoko/media/js/smoothscroll.js"></script>
<script type="text/javascript" src="themes/yoko/media/js/jquery.ui.totop.js"></script>
<script type="text/javascript" src="themes/yoko/media/js/main.js"></script>
<script type="text/javascript" src="themes/yoko/media/js/ajax-mail.js"></script>
<script type="text/javascript" src="themes/yoko/media/js/accordion.settings.js"></script>
<script type="text/javascript" src="themes/yoko/media/js/supersized.3.2.7.min.js"></script>